apiVersion: v1 
kind: ConfigMap 
metadata:
  name: chaosmonkey-configmap
data:
  # Configuration values can be set as key-value properties
  scheduler-fixedrate: "10000"
  scheduler-initialdelay: "5000"
  target-label-key: ""
  target-label-value: ""

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaosmonkeypod
  namespace: default
  labels:
    app: chaosmonkeypod
spec:
  selector:
    matchLabels: 
      app: chaosmonkeypod
  replicas: 1
  template:
    metadata:
      labels:
        app: chaosmonkeypod
    spec:
      containers:
        - name: chaosmonkeypod
          image: riccardo-bottini/chaosmonkey:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          imagePullPolicy: Never
          env:
            - name: scheduler-fixedrate
              valueFrom:
                configMapKeyRef:
                  name: chaosmonkey-configmap
                  key: scheduler-fixedrate
            - name: scheduler-initialdelay
              valueFrom:
                configMapKeyRef:
                  name: chaosmonkey-configmap
                  key: scheduler-initialdelay
            - name: target-label-key
              valueFrom:
                configMapKeyRef:
                  name: chaosmonkey-configmap
                  key: target-label-key
            - name: target-label-value
              valueFrom:
                configMapKeyRef:
                  name: chaosmonkey-configmap
                  key: target-label-value
