apiVersion: v1 
kind: ConfigMap 
metadata:
  name: chaosmonkey-configmap
data:
  # Configuration values can be set as key-value properties
  target-namespace: testing
  scheduler-fixedrate: "10000"
  target-label: ""

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaosmonkeypod
  namespace: default
  labels:
    app: chaosmonkeypod
spec:
  selector:
    matchLabels: 
      app: chaosmonkeypod
  replicas: 1
  template:
    metadata:
      labels:
        app: chaosmonkeypod
    spec:
      containers:
      - name: chaosmonkeypod
        image: riccardo-bottini/chaosmonkey:latest
        imagePullPolicy: Never
        env:
          - name: target-namespace
            valueFrom:
              configMapRef:
                name: chaosmonkey-configmap
                value: target-namespace
          - name: scheduler-fixedrate
            valueFrom:
              configMapRef:
                name: chaosmonkey-configmap
                value: scheduler-fixedrate
          - name: target-label
            valueFrom:
              configMapRef:
                name: chaosmonkey-configmap
                value: target-label
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
